/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-110185-gb564ad8eac-20230406"
#endif /* AVUTIL_FFVERSION_H */
